
import java.awt.Color;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jirawan
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainPage() {

        initComponents();
        //userIdtxt.setVisible(false);
        ProductService.getInfo("1");
        lbl_Page1.setForeground(Color.blue);
        btn_Detail7.setVisible(false);
        btn_Detail8.setVisible(false);
        btn_Detail9.setVisible(false);
        btn_Detail10.setVisible(false);
        btn_Detail11.setVisible(false);
        btn_Detail12.setVisible(false);
        //ProfileForm.lbl_userid.setText(userIdtxt.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Detail1 = new javax.swing.JButton();
        btn_Detail2 = new javax.swing.JButton();
        btn_Detail3 = new javax.swing.JButton();
        btn_Detail4 = new javax.swing.JButton();
        btn_Detail5 = new javax.swing.JButton();
        btn_Detail6 = new javax.swing.JButton();
        btn_Cart = new javax.swing.JButton();
        btn_Profile = new javax.swing.JButton();
        lbl_Pic6 = new javax.swing.JLabel();
        lbl_Pic1 = new javax.swing.JLabel();
        lbl_Pic2 = new javax.swing.JLabel();
        lbl_Pic3 = new javax.swing.JLabel();
        lbl_Pic4 = new javax.swing.JLabel();
        lbl_Pic5 = new javax.swing.JLabel();
        lbl_Name3 = new javax.swing.JLabel();
        lbl_Name1 = new javax.swing.JLabel();
        lbl_Name2 = new javax.swing.JLabel();
        lbl_Name4 = new javax.swing.JLabel();
        lbl_Name5 = new javax.swing.JLabel();
        lbl_Name6 = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        lbl_Page1 = new javax.swing.JLabel();
        lbl_Page2 = new javax.swing.JLabel();
        btn_Detail7 = new javax.swing.JButton();
        btn_Detail8 = new javax.swing.JButton();
        btn_Detail9 = new javax.swing.JButton();
        btn_Detail10 = new javax.swing.JButton();
        btn_Detail11 = new javax.swing.JButton();
        btn_Detail12 = new javax.swing.JButton();
        lbl_icon = new javax.swing.JLabel();
        lbl_nameshop = new javax.swing.JLabel();
        lbl_nameshop1 = new javax.swing.JLabel();
        bgMainpage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        btn_Detail1.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail1.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail1.setText("รายละเอียด");
        btn_Detail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail1);
        btn_Detail1.setBounds(90, 290, 120, 23);

        btn_Detail2.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail2.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail2.setText("รายละเอียด");
        btn_Detail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail2);
        btn_Detail2.setBounds(320, 290, 120, 23);

        btn_Detail3.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail3.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail3.setText("รายละเอียด");
        btn_Detail3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail3);
        btn_Detail3.setBounds(560, 290, 120, 23);

        btn_Detail4.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail4.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail4.setText("รายละเอียด");
        btn_Detail4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail4);
        btn_Detail4.setBounds(90, 480, 120, 23);

        btn_Detail5.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail5.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail5.setText("รายละเอียด");
        btn_Detail5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail5);
        btn_Detail5.setBounds(330, 480, 120, 23);

        btn_Detail6.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail6.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail6.setText("รายละเอียด");
        btn_Detail6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail6);
        btn_Detail6.setBounds(560, 480, 120, 23);

        btn_Cart.setBackground(new java.awt.Color(51, 0, 255));
        btn_Cart.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Cart.setForeground(new java.awt.Color(204, 204, 255));
        btn_Cart.setText("ตะกร้าสินค้า");
        btn_Cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CartActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cart);
        btn_Cart.setBounds(290, 520, 200, 40);

        btn_Profile.setBackground(new java.awt.Color(204, 204, 255));
        btn_Profile.setForeground(new java.awt.Color(102, 0, 204));
        btn_Profile.setText("ข้อมูลส่วนตัว");
        btn_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProfileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Profile);
        btn_Profile.setBounds(600, 20, 100, 23);
        getContentPane().add(lbl_Pic6);
        lbl_Pic6.setBounds(570, 370, 90, 100);

        lbl_Pic1.setMinimumSize(new java.awt.Dimension(120, 200));
        lbl_Pic1.setName("picture1");
        lbl_Pic1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_Pic1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                lbl_Pic1AncestorRemoved(evt);
            }
        });
        getContentPane().add(lbl_Pic1);
        lbl_Pic1.setBounds(100, 180, 100, 100);
        getContentPane().add(lbl_Pic2);
        lbl_Pic2.setBounds(340, 180, 100, 100);
        getContentPane().add(lbl_Pic3);
        lbl_Pic3.setBounds(570, 180, 90, 100);
        getContentPane().add(lbl_Pic4);
        lbl_Pic4.setBounds(100, 370, 100, 100);
        getContentPane().add(lbl_Pic5);
        lbl_Pic5.setBounds(340, 370, 100, 100);

        lbl_Name3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_Name3);
        lbl_Name3.setBounds(570, 150, 170, 20);

        lbl_Name1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_Name1);
        lbl_Name1.setBounds(100, 150, 170, 20);

        lbl_Name2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_Name2);
        lbl_Name2.setBounds(340, 150, 180, 20);

        lbl_Name4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_Name4);
        lbl_Name4.setBounds(100, 340, 160, 20);

        lbl_Name5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_Name5);
        lbl_Name5.setBounds(330, 340, 150, 20);

        lbl_Name6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(lbl_Name6);
        lbl_Name6.setBounds(570, 340, 160, 20);

        btn_Logout.setBackground(new java.awt.Color(255, 0, 0));
        btn_Logout.setForeground(new java.awt.Color(255, 204, 204));
        btn_Logout.setText("ออกระบบ");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Logout);
        btn_Logout.setBounds(700, 20, 80, 23);

        lbl_Page1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Page1.setText("1");
        lbl_Page1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Page1MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_Page1);
        lbl_Page1.setBounds(40, 530, 20, 20);

        lbl_Page2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_Page2.setText("2");
        lbl_Page2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Page2MouseClicked(evt);
            }
        });
        getContentPane().add(lbl_Page2);
        lbl_Page2.setBounds(60, 530, 20, 20);

        btn_Detail7.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail7.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail7.setText("รายละเอียด");
        btn_Detail7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail7);
        btn_Detail7.setBounds(90, 290, 120, 23);

        btn_Detail8.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail8.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail8.setText("รายละเอียด1");
        btn_Detail8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail8);
        btn_Detail8.setBounds(320, 290, 120, 23);

        btn_Detail9.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail9.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail9.setText("รายละเอียด1");
        btn_Detail9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail9);
        btn_Detail9.setBounds(560, 290, 120, 23);

        btn_Detail10.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail10.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail10.setText("รายละเอียด");
        btn_Detail10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail10);
        btn_Detail10.setBounds(90, 480, 120, 23);

        btn_Detail11.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail11.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail11.setText("รายละเอียด");
        btn_Detail11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail11);
        btn_Detail11.setBounds(330, 480, 120, 23);

        btn_Detail12.setBackground(new java.awt.Color(153, 0, 255));
        btn_Detail12.setForeground(new java.awt.Color(204, 204, 255));
        btn_Detail12.setText("รายละเอียด");
        btn_Detail12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Detail12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Detail12);
        btn_Detail12.setBounds(560, 480, 120, 23);

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconshop.png"))); // NOI18N
        getContentPane().add(lbl_icon);
        lbl_icon.setBounds(10, 10, 130, 130);

        lbl_nameshop.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        lbl_nameshop.setText("Clothes Shop");
        getContentPane().add(lbl_nameshop);
        lbl_nameshop.setBounds(150, 20, 400, 80);

        lbl_nameshop1.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        lbl_nameshop1.setForeground(new java.awt.Color(255, 204, 204));
        lbl_nameshop1.setText("Clothes Shop");
        getContentPane().add(lbl_nameshop1);
        lbl_nameshop1.setBounds(160, 20, 400, 80);

        bgMainpage.setForeground(new java.awt.Color(255, 0, 204));
        bgMainpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgMain.png"))); // NOI18N
        getContentPane().add(bgMainpage);
        bgMainpage.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public static void showProfileForm() {
        ProfileForm profile = new ProfileForm();
        profile.show();
    } 
    private void btn_Detail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail2ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S02"));
        ProductDetailForm.pIdtxt.setText("S02");

    }//GEN-LAST:event_btn_Detail2ActionPerformed

    private void btn_Detail3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail3ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S03"));
        ProductDetailForm.pIdtxt.setText("S03");

    }//GEN-LAST:event_btn_Detail3ActionPerformed

    private void btn_Detail4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail4ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S04"));
        ProductDetailForm.pIdtxt.setText("S04");
    }//GEN-LAST:event_btn_Detail4ActionPerformed

    private void btn_Detail5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail5ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S05"));
        ProductDetailForm.pIdtxt.setText("S05");
    }//GEN-LAST:event_btn_Detail5ActionPerformed

    private void btn_Detail6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail6ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S06"));
        ProductDetailForm.pIdtxt.setText("S06");
    }//GEN-LAST:event_btn_Detail6ActionPerformed

    private void btn_CartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CartActionPerformed
        showCartPage();
        // CartService.showList();


    }//GEN-LAST:event_btn_CartActionPerformed

    private void lbl_Pic1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_Pic1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Pic1AncestorAdded

    private void lbl_Pic1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_Pic1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Pic1AncestorRemoved

    private void btn_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProfileActionPerformed
        showProfileForm();
        this.hide();
    }//GEN-LAST:event_btn_ProfileActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        dispose();
        goToLogin();
        dispose();
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void lbl_Page1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Page1MouseClicked
        ProductService.getInfo("1");
        lbl_Page1.setForeground(Color.blue);
        lbl_Page2.setForeground(Color.black);
        btn_Detail1.setVisible(true);
        btn_Detail2.setVisible(true);
        btn_Detail3.setVisible(true);
        btn_Detail4.setVisible(true);
        btn_Detail5.setVisible(true);
        btn_Detail6.setVisible(true);
        btn_Detail7.setVisible(false);
        btn_Detail8.setVisible(false);
        btn_Detail9.setVisible(false);
        btn_Detail10.setVisible(false);
        btn_Detail11.setVisible(false);
        btn_Detail12.setVisible(false);
    }//GEN-LAST:event_lbl_Page1MouseClicked

    private void lbl_Page2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Page2MouseClicked
        ProductService.getInfo("2");
        lbl_Page2.setForeground(Color.blue);
        lbl_Page1.setForeground(Color.black);
        btn_Detail1.setVisible(false);
        btn_Detail2.setVisible(false);
        btn_Detail3.setVisible(false);
        btn_Detail4.setVisible(false);
        btn_Detail5.setVisible(false);
        btn_Detail6.setVisible(false);
        btn_Detail7.setVisible(true);
        btn_Detail8.setVisible(true);
        btn_Detail9.setVisible(true);
        btn_Detail10.setVisible(true);
        btn_Detail11.setVisible(true);
        btn_Detail12.setVisible(true);
    }//GEN-LAST:event_lbl_Page2MouseClicked

    private void btn_Detail7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail7ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S07"));
        ProductDetailForm.pIdtxt.setText("S07");
    }//GEN-LAST:event_btn_Detail7ActionPerformed

    private void btn_Detail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail1ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S01"));
        ProductDetailForm.pIdtxt.setText("S01");

    }//GEN-LAST:event_btn_Detail1ActionPerformed

    private void btn_Detail8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail8ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S08"));
        ProductDetailForm.pIdtxt.setText("S08");
    }//GEN-LAST:event_btn_Detail8ActionPerformed

    private void btn_Detail9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail9ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S09"));
        ProductDetailForm.pIdtxt.setText("S09");
    }//GEN-LAST:event_btn_Detail9ActionPerformed

    private void btn_Detail10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail10ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S10"));
        ProductDetailForm.pIdtxt.setText("S10");
    }//GEN-LAST:event_btn_Detail10ActionPerformed

    private void btn_Detail11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail11ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S11"));
        ProductDetailForm.pIdtxt.setText("S11");
    }//GEN-LAST:event_btn_Detail11ActionPerformed

    private void btn_Detail12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Detail12ActionPerformed
        showProductDetail();
        ProductDetailService.getDetailProduct(ProductService.getProduct("S12"));
        ProductDetailForm.pIdtxt.setText("S12");
    }//GEN-LAST:event_btn_Detail12ActionPerformed

    public static void showProductDetail() {
        ProductDetailForm productdetail = new ProductDetailForm();
        productdetail.setVisible(true);
    }

    public static void showCartPage() {
        CartPage cart = new CartPage();
        cart.setVisible(true);
        CartService.showList();
    }
    public static void goToLogin(){
        new LoginForm().setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgMainpage;
    private javax.swing.JButton btn_Cart;
    private javax.swing.JButton btn_Detail1;
    private javax.swing.JButton btn_Detail10;
    private javax.swing.JButton btn_Detail11;
    private javax.swing.JButton btn_Detail12;
    private javax.swing.JButton btn_Detail2;
    private javax.swing.JButton btn_Detail3;
    private javax.swing.JButton btn_Detail4;
    private javax.swing.JButton btn_Detail5;
    private javax.swing.JButton btn_Detail6;
    private javax.swing.JButton btn_Detail7;
    private javax.swing.JButton btn_Detail8;
    private javax.swing.JButton btn_Detail9;
    public static javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Profile;
    public static javax.swing.JLabel lbl_Name1;
    public static javax.swing.JLabel lbl_Name2;
    public static javax.swing.JLabel lbl_Name3;
    public static javax.swing.JLabel lbl_Name4;
    public static javax.swing.JLabel lbl_Name5;
    public static javax.swing.JLabel lbl_Name6;
    public static javax.swing.JLabel lbl_Page1;
    public static javax.swing.JLabel lbl_Page2;
    public static javax.swing.JLabel lbl_Pic1;
    public static javax.swing.JLabel lbl_Pic2;
    public static javax.swing.JLabel lbl_Pic3;
    public static javax.swing.JLabel lbl_Pic4;
    public static javax.swing.JLabel lbl_Pic5;
    public static javax.swing.JLabel lbl_Pic6;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_nameshop;
    private javax.swing.JLabel lbl_nameshop1;
    // End of variables declaration//GEN-END:variables
}
