import java.util.*;
import javax.swing.JLabel;
public class ProfileForm extends javax.swing.JFrame {

    /**
     * Creates new form ProfileService
     */
    static User user = LoginForm.userCurrent;
    public ProfileForm() {
        initComponents();
        lbl_Username.setText(user.getUsername());
        lbl_Address.setText(user.getAddress());
        lbl_Phone.setText(user.getPhone());
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_changeaddress = new javax.swing.JButton();
        btn_changephone = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_Order = new javax.swing.JButton();
        lbl_Phone = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_Username = new javax.swing.JLabel();
        lbl_icon = new javax.swing.JLabel();
        lbl_icon2 = new javax.swing.JLabel();
        lbl_Profile1 = new javax.swing.JLabel();
        lbl_usernames = new javax.swing.JLabel();
        lbl_addresss = new javax.swing.JLabel();
        lbl_phonee = new javax.swing.JLabel();
        bgProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        btn_changeaddress.setBackground(new java.awt.Color(255, 0, 0));
        btn_changeaddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_changeaddress.setForeground(new java.awt.Color(255, 255, 255));
        btn_changeaddress.setText("เปลี่ยนที่อยู่จัดส่ง");
        btn_changeaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeaddressActionPerformed(evt);
            }
        });
        getContentPane().add(btn_changeaddress);
        btn_changeaddress.setBounds(640, 320, 140, 40);

        btn_changephone.setBackground(new java.awt.Color(255, 0, 0));
        btn_changephone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_changephone.setForeground(new java.awt.Color(255, 255, 255));
        btn_changephone.setText("เปลี่ยนเบอร์โทร");
        btn_changephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changephoneActionPerformed(evt);
            }
        });
        getContentPane().add(btn_changephone);
        btn_changephone.setBounds(640, 390, 140, 40);

        btn_back.setBackground(new java.awt.Color(255, 0, 0));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("กลับ");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(60, 460, 100, 30);

        btn_Order.setBackground(new java.awt.Color(34, 167, 240));
        btn_Order.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Order.setForeground(new java.awt.Color(255, 255, 255));
        btn_Order.setText("รายการสั่งสินค้า");
        btn_Order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Order);
        btn_Order.setBounds(620, 20, 150, 30);

        lbl_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Phone.setText("...");
        getContentPane().add(lbl_Phone);
        lbl_Phone.setBounds(180, 390, 440, 40);

        lbl_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Address.setText("...");
        getContentPane().add(lbl_Address);
        lbl_Address.setBounds(180, 320, 440, 40);

        lbl_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Username.setText("...");
        getContentPane().add(lbl_Username);
        lbl_Username.setBounds(180, 250, 440, 40);

        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconboy.png"))); // NOI18N
        getContentPane().add(lbl_icon);
        lbl_icon.setBounds(400, 170, 60, 70);

        lbl_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icongirl.png"))); // NOI18N
        getContentPane().add(lbl_icon2);
        lbl_icon2.setBounds(340, 170, 60, 70);

        lbl_Profile1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_Profile1.setText("ข้อมูลส่วนตัว");
        getContentPane().add(lbl_Profile1);
        lbl_Profile1.setBounds(50, 160, 290, 90);

        lbl_usernames.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_usernames.setText("ชื่อผู้ใช้ :");
        getContentPane().add(lbl_usernames);
        lbl_usernames.setBounds(80, 250, 100, 40);

        lbl_addresss.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_addresss.setText("ที่อยู่จัดส่ง :");
        getContentPane().add(lbl_addresss);
        lbl_addresss.setBounds(50, 320, 120, 29);

        lbl_phonee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_phonee.setText("เบอร์ :");
        getContentPane().add(lbl_phonee);
        lbl_phonee.setBounds(100, 390, 80, 29);

        bgProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgPro.jpg"))); // NOI18N
        getContentPane().add(bgProfile);
        bgProfile.setBounds(0, 0, 800, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     public static void showChangePhoneForm() {
        ChangePhoneForm phone = new ChangePhoneForm();
        phone.show();
    }

    public static void showChangeAddressForm() {
        ChangeAddressForm address = new ChangeAddressForm();
        address.show();
    }
    public static void showMainPageForm() {
       MainPage mainpage = new MainPage();
        mainpage.show();
    }
    public static void showOrderForm() {
        OrderPage order = new OrderPage();
        order.show();
    }
    private void btn_changephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changephoneActionPerformed
        // TODO add your handling code here:
        showChangePhoneForm();
        this.hide();
    }//GEN-LAST:event_btn_changephoneActionPerformed

    private void btn_changeaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeaddressActionPerformed
        // TODO add your handling code here:
        showChangeAddressForm();
        this.hide();
         
        
    }//GEN-LAST:event_btn_changeaddressActionPerformed

    private void btn_OrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderActionPerformed
        showOrderForm();
        this.hide();
    }//GEN-LAST:event_btn_OrderActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        showMainPageForm();
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgProfile;
    private javax.swing.JButton btn_Order;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_changeaddress;
    private javax.swing.JButton btn_changephone;
    public static javax.swing.JLabel lbl_Address;
    public static javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_Profile1;
    public static javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_addresss;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_icon2;
    private javax.swing.JLabel lbl_phonee;
    private javax.swing.JLabel lbl_usernames;
    // End of variables declaration//GEN-END:variables

    
}
